#
# Use this configuration file to control what RobotPy packages are installed
# on your RoboRIO
#

[tool.robotpy]

# Version of robotpy this project depends on
robotpy_version = "2026.2.1"

# Which extra RobotPy components should be installed
# -> equivalent to `pip install robotpy[extra1, ...]
components = [
    "commands2",
    "pathplannerlib",
    # "all",
    # "apriltag",
    # "cscore",
    # "navx",
    # "phoenix5",
    # "photonvision",
    # "playingwithfusion",
    # "rev",
    # "romi",
    # "sim",
    # "xrp",
]

# Other pip packages to install
requires = [
    "robotpy-commands-v2",
    "pynetworktables",
    "phoenix6",
    "robotpy-rev",
    # "photonlibpy",
]
